volumes:
  pg_data_production:
  static_volume:
  media_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: inswty/foodgram_backend # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media/
      - ./data:/data 
    depends_on:
      - db
  frontend:
    image: inswty/foodgram_frontend  # Качаем с Docker Hub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: inswty/foodgram_gateway  # Качаем с Docker Hub
    env_file: .env
    volumes:
      - static_volume:/staticfiles
      - static_volume:/usr/share/nginx/html
      - media_volume:/media/
    depends_on:
      - backend
    ports:
      - 9080:80