# Generated by Django 3.2.3 on 2025-08-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20250804_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='дата подписки'),
        ),
    ]
